name: Publish unsign version

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  Build-and-release:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install create-dmg
        run: npm i -g create-dmg

      - name: Build Archive
        run: xcodebuild archive -project "MTMR.xcodeproj" -scheme "MTMR" -archivePath Release/App.xcarchive DEVELOPMENT_TEAM="" CODE_SIGN_IDENTITY="" | xcpretty -c && exit ${PIPESTATUS[0]}

      - name: Build App
        run: xcodebuild -project "MTMR.xcodeproj" -exportArchive -archivePath Release/App.xcarchive -exportOptionsPlist export-options.plist -exportPath Release | xcpretty -c && exit ${PIPESTATUS[0]}

      - name: Create DMG
        run: |
          cd Release
          create-dmg MTMR.app || true

      - name: GitHub Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: Release/MTMR*.dmg
